// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file accounts.proto (package accounts, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ContractPointer, PredicatePointer, ScriptPointer } from "./pointers_pb";
import { file_pointers } from "./pointers_pb";
import type { Metadata } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accounts.proto.
 */
export const file_accounts: GenFile = /*@__PURE__*/
  fileDesc("Cg5hY2NvdW50cy5wcm90bxIIYWNjb3VudHMiqAEKCVByZWRpY2F0ZRIjCgR0eXBlGAEgASgOMhUuYWNjb3VudHMuQWNjb3VudFR5cGUSKwoHcG9pbnRlchgCIAEoCzIaLnBvaW50ZXJzLlByZWRpY2F0ZVBvaW50ZXISJQoEZGF0YRgDIAEoCzIXLmFjY291bnRzLlByZWRpY2F0ZURhdGESIgoIbWV0YWRhdGEYBCABKAsyEC5jb21tb24uTWV0YWRhdGEiIQoNUHJlZGljYXRlRGF0YRIQCghieXRlY29kZRgBIAEoCSKlAQoIQ29udHJhY3QSIwoEdHlwZRgBIAEoDjIVLmFjY291bnRzLkFjY291bnRUeXBlEioKB3BvaW50ZXIYAiABKAsyGS5wb2ludGVycy5Db250cmFjdFBvaW50ZXISJAoEZGF0YRgDIAEoCzIWLmFjY291bnRzLkNvbnRyYWN0RGF0YRIiCghtZXRhZGF0YRgEIAEoCzIQLmNvbW1vbi5NZXRhZGF0YSItCgxDb250cmFjdERhdGESEAoIYnl0ZWNvZGUYASABKAkSCwoDYWJpGAIgASgJIp8BCgZTY3JpcHQSIwoEdHlwZRgBIAEoDjIVLmFjY291bnRzLkFjY291bnRUeXBlEigKB3BvaW50ZXIYAiABKAsyFy5wb2ludGVycy5TY3JpcHRQb2ludGVyEiIKBGRhdGEYAyABKAsyFC5hY2NvdW50cy5TY3JpcHREYXRhEiIKCG1ldGFkYXRhGAQgASgLMhAuY29tbW9uLk1ldGFkYXRhIh4KClNjcmlwdERhdGESEAoIYnl0ZWNvZGUYASABKAkqUAoLQWNjb3VudFR5cGUSGAoUVU5LTk9XTl9BQ0NPVU5UX1RZUEUQABINCglQUkVESUNBVEUQARIMCghDT05UUkFDVBACEgoKBlNDUklQVBADYgZwcm90bzM", [file_pointers, file_common]);

/**
 * @generated from message accounts.Predicate
 */
export type Predicate = Message<"accounts.Predicate"> & {
  /**
   * @generated from field: accounts.AccountType type = 1;
   */
  type: AccountType;

  /**
   * @generated from field: pointers.PredicatePointer pointer = 2;
   */
  pointer?: PredicatePointer;

  /**
   * @generated from field: accounts.PredicateData data = 3;
   */
  data?: PredicateData;

  /**
   * @generated from field: common.Metadata metadata = 4;
   */
  metadata?: Metadata;
};

/**
 * Describes the message accounts.Predicate.
 * Use `create(PredicateSchema)` to create a new message.
 */
export const PredicateSchema: GenMessage<Predicate> = /*@__PURE__*/
  messageDesc(file_accounts, 0);

/**
 * @generated from message accounts.PredicateData
 */
export type PredicateData = Message<"accounts.PredicateData"> & {
  /**
   * @generated from field: string bytecode = 1;
   */
  bytecode: string;
};

/**
 * Describes the message accounts.PredicateData.
 * Use `create(PredicateDataSchema)` to create a new message.
 */
export const PredicateDataSchema: GenMessage<PredicateData> = /*@__PURE__*/
  messageDesc(file_accounts, 1);

/**
 * @generated from message accounts.Contract
 */
export type Contract = Message<"accounts.Contract"> & {
  /**
   * @generated from field: accounts.AccountType type = 1;
   */
  type: AccountType;

  /**
   * @generated from field: pointers.ContractPointer pointer = 2;
   */
  pointer?: ContractPointer;

  /**
   * @generated from field: accounts.ContractData data = 3;
   */
  data?: ContractData;

  /**
   * @generated from field: common.Metadata metadata = 4;
   */
  metadata?: Metadata;
};

/**
 * Describes the message accounts.Contract.
 * Use `create(ContractSchema)` to create a new message.
 */
export const ContractSchema: GenMessage<Contract> = /*@__PURE__*/
  messageDesc(file_accounts, 2);

/**
 * @generated from message accounts.ContractData
 */
export type ContractData = Message<"accounts.ContractData"> & {
  /**
   * @generated from field: string bytecode = 1;
   */
  bytecode: string;

  /**
   * @generated from field: string abi = 2;
   */
  abi: string;
};

/**
 * Describes the message accounts.ContractData.
 * Use `create(ContractDataSchema)` to create a new message.
 */
export const ContractDataSchema: GenMessage<ContractData> = /*@__PURE__*/
  messageDesc(file_accounts, 3);

/**
 * @generated from message accounts.Script
 */
export type Script = Message<"accounts.Script"> & {
  /**
   * @generated from field: accounts.AccountType type = 1;
   */
  type: AccountType;

  /**
   * @generated from field: pointers.ScriptPointer pointer = 2;
   */
  pointer?: ScriptPointer;

  /**
   * @generated from field: accounts.ScriptData data = 3;
   */
  data?: ScriptData;

  /**
   * @generated from field: common.Metadata metadata = 4;
   */
  metadata?: Metadata;
};

/**
 * Describes the message accounts.Script.
 * Use `create(ScriptSchema)` to create a new message.
 */
export const ScriptSchema: GenMessage<Script> = /*@__PURE__*/
  messageDesc(file_accounts, 4);

/**
 * @generated from message accounts.ScriptData
 */
export type ScriptData = Message<"accounts.ScriptData"> & {
  /**
   * @generated from field: string bytecode = 1;
   */
  bytecode: string;
};

/**
 * Describes the message accounts.ScriptData.
 * Use `create(ScriptDataSchema)` to create a new message.
 */
export const ScriptDataSchema: GenMessage<ScriptData> = /*@__PURE__*/
  messageDesc(file_accounts, 5);

/**
 * @generated from enum accounts.AccountType
 */
export enum AccountType {
  /**
   * @generated from enum value: UNKNOWN_ACCOUNT_TYPE = 0;
   */
  UNKNOWN_ACCOUNT_TYPE = 0,

  /**
   * @generated from enum value: PREDICATE = 1;
   */
  PREDICATE = 1,

  /**
   * @generated from enum value: CONTRACT = 2;
   */
  CONTRACT = 2,

  /**
   * @generated from enum value: SCRIPT = 3;
   */
  SCRIPT = 3,
}

/**
 * Describes the enum accounts.AccountType.
 */
export const AccountTypeSchema: GenEnum<AccountType> = /*@__PURE__*/
  enumDesc(file_accounts, 0);

