// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file utxos.proto (package utxos, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { UtxoPointer } from "./pointers_pb";
import { file_pointers } from "./pointers_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file utxos.proto.
 */
export const file_utxos: GenFile = /*@__PURE__*/
  fileDesc("Cgt1dHhvcy5wcm90bxIFdXR4b3MiwQMKBFV0eG8SDwoHc3ViamVjdBgBIAEoCRIUCgxibG9ja19oZWlnaHQYAiABKAMSDQoFdHhfaWQYAyABKAwSEAoIdHhfaW5kZXgYBCABKAUSEwoLaW5wdXRfaW5kZXgYBSABKAUSIgoJdXR4b190eXBlGAYgASgOMg8udXR4b3MuVXR4b1R5cGUSDwoHdXR4b19pZBgHIAEoDBINCgV2YWx1ZRgIIAEoDBIWCg5zZW5kZXJfYWRkcmVzcxgJIAEoDBIZChFyZWNpcGllbnRfYWRkcmVzcxgKIAEoDBINCgVub25jZRgLIAEoDBIOCgZhbW91bnQYDCABKAMSDAoEZGF0YRgNIAEoDBIuCgpjcmVhdGVkX2F0GA4gASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgxwdWJsaXNoZWRfYXQYDyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYECABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiYKB3BvaW50ZXIYESABKAsyFS5wb2ludGVycy5VdHhvUG9pbnRlciovCghVdHhvVHlwZRIMCghDT05UUkFDVBAAEggKBENPSU4QARILCgdNRVNTQUdFEAJiBnByb3RvMw", [file_google_protobuf_timestamp, file_pointers]);

/**
 * @generated from message utxos.Utxo
 */
export type Utxo = Message<"utxos.Utxo"> & {
  /**
   * @generated from field: string subject = 1;
   */
  subject: string;

  /**
   * @generated from field: int64 block_height = 2;
   */
  blockHeight: bigint;

  /**
   * @generated from field: bytes tx_id = 3;
   */
  txId: Uint8Array;

  /**
   * @generated from field: int32 tx_index = 4;
   */
  txIndex: number;

  /**
   * @generated from field: int32 input_index = 5;
   */
  inputIndex: number;

  /**
   * @generated from field: utxos.UtxoType utxo_type = 6;
   */
  utxoType: UtxoType;

  /**
   * @generated from field: bytes utxo_id = 7;
   */
  utxoId: Uint8Array;

  /**
   * @generated from field: bytes value = 8;
   */
  value: Uint8Array;

  /**
   * @generated from field: bytes sender_address = 9;
   */
  senderAddress: Uint8Array;

  /**
   * @generated from field: bytes recipient_address = 10;
   */
  recipientAddress: Uint8Array;

  /**
   * @generated from field: bytes nonce = 11;
   */
  nonce: Uint8Array;

  /**
   * @generated from field: int64 amount = 12;
   */
  amount: bigint;

  /**
   * @generated from field: bytes data = 13;
   */
  data: Uint8Array;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 14;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp published_at = 15;
   */
  publishedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 16;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: pointers.UtxoPointer pointer = 17;
   */
  pointer?: UtxoPointer;
};

/**
 * Describes the message utxos.Utxo.
 * Use `create(UtxoSchema)` to create a new message.
 */
export const UtxoSchema: GenMessage<Utxo> = /*@__PURE__*/
  messageDesc(file_utxos, 0);

/**
 * @generated from enum utxos.UtxoType
 */
export enum UtxoType {
  /**
   * @generated from enum value: CONTRACT = 0;
   */
  CONTRACT = 0,

  /**
   * @generated from enum value: COIN = 1;
   */
  COIN = 1,

  /**
   * @generated from enum value: MESSAGE = 2;
   */
  MESSAGE = 2,
}

/**
 * Describes the enum utxos.UtxoType.
 */
export const UtxoTypeSchema: GenEnum<UtxoType> = /*@__PURE__*/
  enumDesc(file_utxos, 0);

