---
includes: [proto]
files:
  - proto/accounts.proto
  - proto/common.proto
  - proto/assets.proto
  - proto/blocks.proto
  - proto/transactions.proto
  - proto/inputs.proto
  - proto/outputs.proto
  - proto/receipts.proto
  - proto/utxos.proto
  - proto/pointers.proto
output: src/proto
messages:
  - paths: []
    attrs: []
enums:
  - paths: []
    attrs: []
fields:
  - paths: []
    attrs: []

btree_map: ["."]
bytes: ["."]
