[package]
name = "your_project"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
prost-types = "0.13"
tonic = { version = "0.12", optional = true }

[build-dependencies]
prost-build = "0.13"