// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: outputs.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Metadata } from "./common";
import { OutputPointer } from "./pointers";

export const protobufPackage = "outputs";

export enum OutputType {
  UNKNOWN_OUTPUT_TYPE = 0,
  COIN = 1,
  CONTRACT = 2,
  CHANGE = 3,
  VARIABLE = 4,
  CONTRACT_CREATED = 5,
  UNRECOGNIZED = -1,
}

export function outputTypeFromJSON(object: any): OutputType {
  switch (object) {
    case 0:
    case "UNKNOWN_OUTPUT_TYPE":
      return OutputType.UNKNOWN_OUTPUT_TYPE;
    case 1:
    case "COIN":
      return OutputType.COIN;
    case 2:
    case "CONTRACT":
      return OutputType.CONTRACT;
    case 3:
    case "CHANGE":
      return OutputType.CHANGE;
    case 4:
    case "VARIABLE":
      return OutputType.VARIABLE;
    case 5:
    case "CONTRACT_CREATED":
      return OutputType.CONTRACT_CREATED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OutputType.UNRECOGNIZED;
  }
}

export function outputTypeToJSON(object: OutputType): string {
  switch (object) {
    case OutputType.UNKNOWN_OUTPUT_TYPE:
      return "UNKNOWN_OUTPUT_TYPE";
    case OutputType.COIN:
      return "COIN";
    case OutputType.CONTRACT:
      return "CONTRACT";
    case OutputType.CHANGE:
      return "CHANGE";
    case OutputType.VARIABLE:
      return "VARIABLE";
    case OutputType.CONTRACT_CREATED:
      return "CONTRACT_CREATED";
    case OutputType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Output {
  subject: string;
  type: OutputType;
  coin?: OutputCoin | undefined;
  contract?: OutputContract | undefined;
  change?: OutputChange | undefined;
  variable?: OutputVariable | undefined;
  contractCreated?:
    | OutputContractCreated
    | undefined;
  /** Metadata */
  metadata: Metadata | undefined;
  pointer: OutputPointer | undefined;
}

export interface OutputCoin {
  to: Uint8Array;
  amount: number;
  assetId: Uint8Array;
}

export interface OutputContract {
  balanceRoot: Uint8Array;
  stateRoot: Uint8Array;
  inputIndex: number;
}

export interface OutputContractCreated {
  contractId: Uint8Array;
  stateRoot: Uint8Array;
}

export interface OutputChange {
  to: Uint8Array;
  amount: number;
  assetId: Uint8Array;
}

export interface OutputVariable {
  to: Uint8Array;
  amount: number;
  assetId: Uint8Array;
}

function createBaseOutput(): Output {
  return {
    subject: "",
    type: 0,
    coin: undefined,
    contract: undefined,
    change: undefined,
    variable: undefined,
    contractCreated: undefined,
    metadata: undefined,
    pointer: undefined,
  };
}

export const Output: MessageFns<Output> = {
  encode(message: Output, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subject !== "") {
      writer.uint32(10).string(message.subject);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.coin !== undefined) {
      OutputCoin.encode(message.coin, writer.uint32(26).fork()).join();
    }
    if (message.contract !== undefined) {
      OutputContract.encode(message.contract, writer.uint32(34).fork()).join();
    }
    if (message.change !== undefined) {
      OutputChange.encode(message.change, writer.uint32(42).fork()).join();
    }
    if (message.variable !== undefined) {
      OutputVariable.encode(message.variable, writer.uint32(50).fork()).join();
    }
    if (message.contractCreated !== undefined) {
      OutputContractCreated.encode(message.contractCreated, writer.uint32(58).fork()).join();
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(74).fork()).join();
    }
    if (message.pointer !== undefined) {
      OutputPointer.encode(message.pointer, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Output {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.coin = OutputCoin.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contract = OutputContract.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.change = OutputChange.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.variable = OutputVariable.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.contractCreated = OutputContractCreated.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.pointer = OutputPointer.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Output {
    return {
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      type: isSet(object.type) ? outputTypeFromJSON(object.type) : 0,
      coin: isSet(object.coin) ? OutputCoin.fromJSON(object.coin) : undefined,
      contract: isSet(object.contract) ? OutputContract.fromJSON(object.contract) : undefined,
      change: isSet(object.change) ? OutputChange.fromJSON(object.change) : undefined,
      variable: isSet(object.variable) ? OutputVariable.fromJSON(object.variable) : undefined,
      contractCreated: isSet(object.contractCreated)
        ? OutputContractCreated.fromJSON(object.contractCreated)
        : undefined,
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
      pointer: isSet(object.pointer) ? OutputPointer.fromJSON(object.pointer) : undefined,
    };
  },

  toJSON(message: Output): unknown {
    const obj: any = {};
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.type !== 0) {
      obj.type = outputTypeToJSON(message.type);
    }
    if (message.coin !== undefined) {
      obj.coin = OutputCoin.toJSON(message.coin);
    }
    if (message.contract !== undefined) {
      obj.contract = OutputContract.toJSON(message.contract);
    }
    if (message.change !== undefined) {
      obj.change = OutputChange.toJSON(message.change);
    }
    if (message.variable !== undefined) {
      obj.variable = OutputVariable.toJSON(message.variable);
    }
    if (message.contractCreated !== undefined) {
      obj.contractCreated = OutputContractCreated.toJSON(message.contractCreated);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.pointer !== undefined) {
      obj.pointer = OutputPointer.toJSON(message.pointer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Output>, I>>(base?: I): Output {
    return Output.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Output>, I>>(object: I): Output {
    const message = createBaseOutput();
    message.subject = object.subject ?? "";
    message.type = object.type ?? 0;
    message.coin = (object.coin !== undefined && object.coin !== null)
      ? OutputCoin.fromPartial(object.coin)
      : undefined;
    message.contract = (object.contract !== undefined && object.contract !== null)
      ? OutputContract.fromPartial(object.contract)
      : undefined;
    message.change = (object.change !== undefined && object.change !== null)
      ? OutputChange.fromPartial(object.change)
      : undefined;
    message.variable = (object.variable !== undefined && object.variable !== null)
      ? OutputVariable.fromPartial(object.variable)
      : undefined;
    message.contractCreated = (object.contractCreated !== undefined && object.contractCreated !== null)
      ? OutputContractCreated.fromPartial(object.contractCreated)
      : undefined;
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    message.pointer = (object.pointer !== undefined && object.pointer !== null)
      ? OutputPointer.fromPartial(object.pointer)
      : undefined;
    return message;
  },
};

function createBaseOutputCoin(): OutputCoin {
  return { to: new Uint8Array(0), amount: 0, assetId: new Uint8Array(0) };
}

export const OutputCoin: MessageFns<OutputCoin> = {
  encode(message: OutputCoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to.length !== 0) {
      writer.uint32(10).bytes(message.to);
    }
    if (message.amount !== 0) {
      writer.uint32(16).int64(message.amount);
    }
    if (message.assetId.length !== 0) {
      writer.uint32(26).bytes(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutputCoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutputCoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.assetId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutputCoin {
    return {
      to: isSet(object.to) ? bytesFromBase64(object.to) : new Uint8Array(0),
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      assetId: isSet(object.assetId) ? bytesFromBase64(object.assetId) : new Uint8Array(0),
    };
  },

  toJSON(message: OutputCoin): unknown {
    const obj: any = {};
    if (message.to.length !== 0) {
      obj.to = base64FromBytes(message.to);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.assetId.length !== 0) {
      obj.assetId = base64FromBytes(message.assetId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OutputCoin>, I>>(base?: I): OutputCoin {
    return OutputCoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutputCoin>, I>>(object: I): OutputCoin {
    const message = createBaseOutputCoin();
    message.to = object.to ?? new Uint8Array(0);
    message.amount = object.amount ?? 0;
    message.assetId = object.assetId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseOutputContract(): OutputContract {
  return { balanceRoot: new Uint8Array(0), stateRoot: new Uint8Array(0), inputIndex: 0 };
}

export const OutputContract: MessageFns<OutputContract> = {
  encode(message: OutputContract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.balanceRoot.length !== 0) {
      writer.uint32(10).bytes(message.balanceRoot);
    }
    if (message.stateRoot.length !== 0) {
      writer.uint32(18).bytes(message.stateRoot);
    }
    if (message.inputIndex !== 0) {
      writer.uint32(24).int32(message.inputIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutputContract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutputContract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.balanceRoot = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stateRoot = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.inputIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutputContract {
    return {
      balanceRoot: isSet(object.balanceRoot) ? bytesFromBase64(object.balanceRoot) : new Uint8Array(0),
      stateRoot: isSet(object.stateRoot) ? bytesFromBase64(object.stateRoot) : new Uint8Array(0),
      inputIndex: isSet(object.inputIndex) ? globalThis.Number(object.inputIndex) : 0,
    };
  },

  toJSON(message: OutputContract): unknown {
    const obj: any = {};
    if (message.balanceRoot.length !== 0) {
      obj.balanceRoot = base64FromBytes(message.balanceRoot);
    }
    if (message.stateRoot.length !== 0) {
      obj.stateRoot = base64FromBytes(message.stateRoot);
    }
    if (message.inputIndex !== 0) {
      obj.inputIndex = Math.round(message.inputIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OutputContract>, I>>(base?: I): OutputContract {
    return OutputContract.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutputContract>, I>>(object: I): OutputContract {
    const message = createBaseOutputContract();
    message.balanceRoot = object.balanceRoot ?? new Uint8Array(0);
    message.stateRoot = object.stateRoot ?? new Uint8Array(0);
    message.inputIndex = object.inputIndex ?? 0;
    return message;
  },
};

function createBaseOutputContractCreated(): OutputContractCreated {
  return { contractId: new Uint8Array(0), stateRoot: new Uint8Array(0) };
}

export const OutputContractCreated: MessageFns<OutputContractCreated> = {
  encode(message: OutputContractCreated, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contractId.length !== 0) {
      writer.uint32(10).bytes(message.contractId);
    }
    if (message.stateRoot.length !== 0) {
      writer.uint32(18).bytes(message.stateRoot);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutputContractCreated {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutputContractCreated();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contractId = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stateRoot = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutputContractCreated {
    return {
      contractId: isSet(object.contractId) ? bytesFromBase64(object.contractId) : new Uint8Array(0),
      stateRoot: isSet(object.stateRoot) ? bytesFromBase64(object.stateRoot) : new Uint8Array(0),
    };
  },

  toJSON(message: OutputContractCreated): unknown {
    const obj: any = {};
    if (message.contractId.length !== 0) {
      obj.contractId = base64FromBytes(message.contractId);
    }
    if (message.stateRoot.length !== 0) {
      obj.stateRoot = base64FromBytes(message.stateRoot);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OutputContractCreated>, I>>(base?: I): OutputContractCreated {
    return OutputContractCreated.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutputContractCreated>, I>>(object: I): OutputContractCreated {
    const message = createBaseOutputContractCreated();
    message.contractId = object.contractId ?? new Uint8Array(0);
    message.stateRoot = object.stateRoot ?? new Uint8Array(0);
    return message;
  },
};

function createBaseOutputChange(): OutputChange {
  return { to: new Uint8Array(0), amount: 0, assetId: new Uint8Array(0) };
}

export const OutputChange: MessageFns<OutputChange> = {
  encode(message: OutputChange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to.length !== 0) {
      writer.uint32(10).bytes(message.to);
    }
    if (message.amount !== 0) {
      writer.uint32(16).int64(message.amount);
    }
    if (message.assetId.length !== 0) {
      writer.uint32(26).bytes(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutputChange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutputChange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.assetId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutputChange {
    return {
      to: isSet(object.to) ? bytesFromBase64(object.to) : new Uint8Array(0),
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      assetId: isSet(object.assetId) ? bytesFromBase64(object.assetId) : new Uint8Array(0),
    };
  },

  toJSON(message: OutputChange): unknown {
    const obj: any = {};
    if (message.to.length !== 0) {
      obj.to = base64FromBytes(message.to);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.assetId.length !== 0) {
      obj.assetId = base64FromBytes(message.assetId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OutputChange>, I>>(base?: I): OutputChange {
    return OutputChange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutputChange>, I>>(object: I): OutputChange {
    const message = createBaseOutputChange();
    message.to = object.to ?? new Uint8Array(0);
    message.amount = object.amount ?? 0;
    message.assetId = object.assetId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseOutputVariable(): OutputVariable {
  return { to: new Uint8Array(0), amount: 0, assetId: new Uint8Array(0) };
}

export const OutputVariable: MessageFns<OutputVariable> = {
  encode(message: OutputVariable, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to.length !== 0) {
      writer.uint32(10).bytes(message.to);
    }
    if (message.amount !== 0) {
      writer.uint32(16).int64(message.amount);
    }
    if (message.assetId.length !== 0) {
      writer.uint32(26).bytes(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutputVariable {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutputVariable();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.assetId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutputVariable {
    return {
      to: isSet(object.to) ? bytesFromBase64(object.to) : new Uint8Array(0),
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      assetId: isSet(object.assetId) ? bytesFromBase64(object.assetId) : new Uint8Array(0),
    };
  },

  toJSON(message: OutputVariable): unknown {
    const obj: any = {};
    if (message.to.length !== 0) {
      obj.to = base64FromBytes(message.to);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.assetId.length !== 0) {
      obj.assetId = base64FromBytes(message.assetId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OutputVariable>, I>>(base?: I): OutputVariable {
    return OutputVariable.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutputVariable>, I>>(object: I): OutputVariable {
    const message = createBaseOutputVariable();
    message.to = object.to ?? new Uint8Array(0);
    message.amount = object.amount ?? 0;
    message.assetId = object.assetId ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
