// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Input {
    #[prost(enumeration = "InputType", tag = "1")]
    pub r#type: i32,
    #[prost(message, optional, tag = "2")]
    pub pointer: ::core::option::Option<super::pointers::InputPointer>,
    /// Metadata
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<super::common::Metadata>,
    #[prost(oneof = "input::Data", tags = "3, 4, 5")]
    pub data: ::core::option::Option<input::Data>,
}
/// Nested message and enum types in `Input`.
pub mod input {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        Coin(super::InputCoin),
        #[prost(message, tag = "4")]
        Contract(super::InputContract),
        #[prost(message, tag = "5")]
        Message(super::InputMessage),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InputCoin {
    /// Fields matching fuel-core
    #[prost(string, tag = "1")]
    pub utxo_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub asset_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub witness_index: i32,
    #[prost(int64, tag = "6")]
    pub predicate_gas_used: i64,
    #[prost(string, tag = "7")]
    pub predicate: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub predicate_data: ::prost::alloc::string::String,
    /// Extra fields (not in fuel-core)
    #[prost(int64, tag = "9")]
    pub predicate_length: i64,
    #[prost(int64, tag = "10")]
    pub predicate_data_length: i64,
    #[prost(int32, tag = "11")]
    pub output_index: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InputContract {
    /// Fields matching fuel-core
    #[prost(string, tag = "1")]
    pub utxo_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub balance_root: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state_root: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub contract_id: ::prost::alloc::string::String,
    /// Extra fields (not in fuel-core)
    #[prost(int32, tag = "5")]
    pub output_index: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InputMessage {
    /// Fields matching fuel-core
    #[prost(string, tag = "1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(string, tag = "4")]
    pub nonce: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub witness_index: i32,
    #[prost(int64, tag = "6")]
    pub predicate_gas_used: i64,
    #[prost(string, tag = "7")]
    pub data: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub predicate: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub predicate_data: ::prost::alloc::string::String,
    /// Extra fields (not in fuel-core)
    #[prost(int32, tag = "10")]
    pub data_length: i32,
    #[prost(int32, tag = "11")]
    pub predicate_length: i32,
    #[prost(int32, tag = "12")]
    pub predicate_data_length: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InputType {
    UnknownInputType = 0,
    Contract = 1,
    Coin = 2,
    Message = 3,
}
impl InputType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownInputType => "UNKNOWN_INPUT_TYPE",
            Self::Contract => "CONTRACT",
            Self::Coin => "COIN",
            Self::Message => "MESSAGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_INPUT_TYPE" => Some(Self::UnknownInputType),
            "CONTRACT" => Some(Self::Contract),
            "COIN" => Some(Self::Coin),
            "MESSAGE" => Some(Self::Message),
            _ => None,
        }
    }
}
