// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Receipt {
    #[prost(enumeration = "ReceiptType", tag = "1")]
    #[serde(rename = "type")]
    pub r#type: i32,
    #[prost(message, optional, tag = "2")]
    pub pointer: ::core::option::Option<super::pointers::ReceiptPointer>,
    /// Metadata
    #[prost(message, optional, tag = "16")]
    pub metadata: ::core::option::Option<super::common::Metadata>,
    #[prost(
        oneof = "receipt::Data",
        tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15"
    )]
    #[serde(flatten)]
    pub data: ::core::option::Option<receipt::Data>,
}
/// Nested message and enum types in `Receipt`.
pub mod receipt {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "SCREAMING_SNAKE_CASE")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        Call(super::ReceiptCall),
        #[prost(message, tag = "4")]
        Return(super::ReceiptReturn),
        #[prost(message, tag = "5")]
        ReturnData(super::ReceiptReturnData),
        #[prost(message, tag = "6")]
        Panic(super::ReceiptPanic),
        #[prost(message, tag = "7")]
        Revert(super::ReceiptRevert),
        #[prost(message, tag = "8")]
        Log(super::ReceiptLog),
        #[prost(message, tag = "9")]
        LogData(super::ReceiptLogData),
        #[prost(message, tag = "10")]
        Transfer(super::ReceiptTransfer),
        #[prost(message, tag = "11")]
        TransferOut(super::ReceiptTransferOut),
        #[prost(message, tag = "12")]
        ScriptResult(super::ReceiptScriptResult),
        #[prost(message, tag = "13")]
        MessageOut(super::ReceiptMessageOut),
        #[prost(message, tag = "14")]
        Mint(super::ReceiptMint),
        #[prost(message, tag = "15")]
        Burn(super::ReceiptBurn),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptCall {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub asset_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "5")]
    pub gas: i64,
    #[prost(int64, tag = "6")]
    pub param1: i64,
    #[prost(int64, tag = "7")]
    pub param2: i64,
    #[prost(int64, tag = "8")]
    pub pc: i64,
    #[prost(int64, tag = "9")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptReturn {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub val: i64,
    #[prost(int64, tag = "3")]
    pub pc: i64,
    #[prost(int64, tag = "4")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptReturnData {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub ptr: i64,
    #[prost(int64, tag = "3")]
    pub len: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "6")]
    pub pc: i64,
    #[prost(int64, tag = "7")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptPanic {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub reason: i64,
    #[prost(int64, tag = "3")]
    pub pc: i64,
    #[prost(int64, tag = "4")]
    pub is: i64,
    #[prost(bytes = "vec", tag = "5")]
    pub contract_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptRevert {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub ra: i64,
    #[prost(int64, tag = "3")]
    pub pc: i64,
    #[prost(int64, tag = "4")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptLog {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub ra: i64,
    #[prost(int64, tag = "3")]
    pub rb: i64,
    #[prost(int64, tag = "4")]
    pub rc: i64,
    #[prost(int64, tag = "5")]
    pub rd: i64,
    #[prost(int64, tag = "6")]
    pub pc: i64,
    #[prost(int64, tag = "7")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptLogData {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "2")]
    pub ra: i64,
    #[prost(int64, tag = "3")]
    pub rb: i64,
    #[prost(int64, tag = "4")]
    pub ptr: i64,
    #[prost(int64, tag = "5")]
    pub len: i64,
    #[prost(bytes = "vec", tag = "6")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "7")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "8")]
    pub pc: i64,
    #[prost(int64, tag = "9")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptTransfer {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub asset_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "5")]
    pub pc: i64,
    #[prost(int64, tag = "6")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptTransferOut {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub asset_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "5")]
    pub pc: i64,
    #[prost(int64, tag = "6")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReceiptScriptResult {
    #[prost(enumeration = "ScriptResultType", tag = "1")]
    pub result: i32,
    #[prost(int64, tag = "2")]
    pub gas_used: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptMessageOut {
    #[prost(bytes = "vec", tag = "1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub amount: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "5")]
    pub len: i64,
    #[prost(bytes = "vec", tag = "6")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "7")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptMint {
    #[prost(bytes = "vec", tag = "1")]
    pub sub_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub asset_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "4")]
    pub val: i64,
    #[prost(int64, tag = "5")]
    pub pc: i64,
    #[prost(int64, tag = "6")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptBurn {
    #[prost(bytes = "vec", tag = "1")]
    pub sub_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub asset_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "4")]
    pub val: i64,
    #[prost(int64, tag = "5")]
    pub pc: i64,
    #[prost(int64, tag = "6")]
    pub is: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReceiptType {
    UnknownReceiptType = 0,
    Call = 1,
    Return = 2,
    ReturnData = 3,
    Panic = 4,
    Revert = 5,
    Log = 6,
    LogData = 7,
    Transfer = 8,
    TransferOut = 9,
    ScriptResult = 10,
    MessageOut = 11,
    Mint = 12,
    Burn = 13,
}
impl ReceiptType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownReceiptType => "UNKNOWN_RECEIPT_TYPE",
            Self::Call => "CALL",
            Self::Return => "RETURN",
            Self::ReturnData => "RETURN_DATA",
            Self::Panic => "PANIC",
            Self::Revert => "REVERT",
            Self::Log => "LOG",
            Self::LogData => "LOG_DATA",
            Self::Transfer => "TRANSFER",
            Self::TransferOut => "TRANSFER_OUT",
            Self::ScriptResult => "SCRIPT_RESULT",
            Self::MessageOut => "MESSAGE_OUT",
            Self::Mint => "MINT",
            Self::Burn => "BURN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_RECEIPT_TYPE" => Some(Self::UnknownReceiptType),
            "CALL" => Some(Self::Call),
            "RETURN" => Some(Self::Return),
            "RETURN_DATA" => Some(Self::ReturnData),
            "PANIC" => Some(Self::Panic),
            "REVERT" => Some(Self::Revert),
            "LOG" => Some(Self::Log),
            "LOG_DATA" => Some(Self::LogData),
            "TRANSFER" => Some(Self::Transfer),
            "TRANSFER_OUT" => Some(Self::TransferOut),
            "SCRIPT_RESULT" => Some(Self::ScriptResult),
            "MESSAGE_OUT" => Some(Self::MessageOut),
            "MINT" => Some(Self::Mint),
            "BURN" => Some(Self::Burn),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScriptResultType {
    UnknownScriptResultType = 0,
    Success = 1,
    ScriptRevert = 2,
    ScriptPanic = 3,
    GenericFailure = 4,
}
impl ScriptResultType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownScriptResultType => "UNKNOWN_SCRIPT_RESULT_TYPE",
            Self::Success => "SUCCESS",
            Self::ScriptRevert => "SCRIPT_REVERT",
            Self::ScriptPanic => "SCRIPT_PANIC",
            Self::GenericFailure => "GENERIC_FAILURE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_SCRIPT_RESULT_TYPE" => Some(Self::UnknownScriptResultType),
            "SUCCESS" => Some(Self::Success),
            "SCRIPT_REVERT" => Some(Self::ScriptRevert),
            "SCRIPT_PANIC" => Some(Self::ScriptPanic),
            "GENERIC_FAILURE" => Some(Self::GenericFailure),
            _ => None,
        }
    }
}
